# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # The container the job will run in
    container:
      image: archlinux:base-devel
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download needed packages
        run: pacman -Syu --noconfirm git pacman-contrib devtools

      - run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      
      - name: Checkout pkgbuilds repo
        uses: actions/checkout@v3
        with:
          path: arch-pkgbuilds

      - name: Checkout DB repo
        uses: actions/checkout@v3
        with:
          repository: FelixFeuerigel/arch-repo
          path: arch-repo

      # Runs a set of commands using the container shell
      - name: Run a multi-line script
        run: |
          pwd
          ls -al
          ./.github/workflows/build.sh -m "GitHub actions"
